version: '3.3'

services:
  php:
    container_name: php
    build:
      context: ./php
    networks:
      - server-net
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - mongo
      - mongo-express

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - server-net
    ports:
      - '3030:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - server-net
#      server-net:
#        ipv4_address: 172.24.0.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - server-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  server-net:
    driver: bridge
